before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Yonas Habteab"
  - git config --local user.email "yonas.habteab@icinga.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
  deploy:
    provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
      tags: true
    draft: true
